services:
  db:
    image: mysql:9.4.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=trilha_api
      - MYSQL_USER=user_api
      - MYSQL_PASSWORD=user_pass